sudo: reuired
services:
  - docker
language: python
python:
  - 2.7
  - pypy
  - 3.3
  - 3.4
  - 3.5
before_install:
  - docker pull tray/dynamodb-local
  - docker run -d -p 7777:7777 tray/dynamodb-local -inMemory -port 7777
  - mkdir /home/travis/.aws
  - printf "[default]\nregion=us-east-1\noutput=json\n" > /home/travis/.aws/config
  - printf "[default]\naws_access_key_id = FAKE0000000000000000\naws_secret_access_key = FAKE000000000000000000000000000000000000\n" > /home/travis/.aws/credentials
install:
  - pip install -r test-requirements.txt
env:
  DYNAMODB_ENDPOINT: http://localhost:7777
script:  nosetests
after_success:
  - codecov
deploy:
  distributions: sdist bdist_wheel
  provider: pypi
  user: crad
  on:
    python: 3.5
    tags: true
    all_branches: true
  password:
    secure: "BsyZPNIC1jfv2i3TzxrYIQUYUHEDPG/5KVdsKZcrYGC+1j7eIMEetBtvK1clnqdnSxhVb85QQy3vuN28QLZgCX1uH4cakKlrMBT1j1Mky7sAOGUnVAZPVMPCSI2Ix+XfbPQMqgnXSnhjcMoUECZw0W75p0mWmjR1PHJAEQSiXImF8ZCzkhpu/8LiVvITHdQXh0fNB7i0hxVFNwMZV5vvU9UmJYuK0QO+V9BTg4SKQaRwe8HmWQEsuhXv7S3q8l3Syg3hmJAGvLQRzykcC6TnDn4X0y3DNFV9D6jTdGAtdu9+uGP8+4goJsph/Jw5L0fnXs1nemdqhPkDMCqzdNGsw6x7chzJck/cQnEvFCpa6mCdBsG6ZAEGf5nuCBixqyoyv/dIGlC3b5USzHrhq+j/HEzjgNdAI4bdtM34L4hLNQ6HUyGX6/c9WfDYUp5mqgGJ0guBNnLs1ZHy208C6i+mnzQc2gudL2EmsMNZSWBXsNT8JPFLQ+x3UjhqHywu/9x68DA68O1ChaRQjf1EyIkQqXZqBOVXGpEhnpqmoOaCDNwjZqICHnnoBJBbGs3qD54caT+CEw8aZ5ceeTR8Stro+4pnDuIc8oZfUe/c1oc/ykG41QQCv+4smfZxS9Uq1q6RB2PYdYy98g8PQK50/FFHRWDUyrN6IYzvxPbe/TDvSFs="
cache:
  directories:
    - $HOME/.pip-cache/
